"""Shared source policy for proposed edits and independent Git diff checks."""
import re
from collections import Counter
from pathlib import Path

READ_WHOLE_LIMIT = 200
READ_WINDOW_LIMIT = 100
SOURCE_SUFFIXES = {'.c', '.h', '.cpp', '.hpp', '.cc'}
BINARY_SUFFIXES = {'.bin', '.hex', '.elf', '.o', '.a'}
MARKER = re.compile(r'^\s*/\* USER CODE (BEGIN|END) (.+?) \*/\s*$')
LEXICAL = re.compile(r'/\*.*?\*/|//[^\n]*|"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'', re.S)
ALLOC = re.compile(r'\b(malloc|calloc|realloc|free|pvPortMalloc|vPortFree)\s*\(')
HAL = re.compile(r'\bHAL_\w+\s*\(|\b(?:ADC|SPI|I2C|UART|USART|GPIO|TIM|DMA)\d*\s*->')


class PolicyError(ValueError):
    """An operation cannot be safely checked or violates a policy."""


def protected(path):
    path = Path(path)
    parts = [part.lower() for part in path.parts]
    return (path.suffix.lower() == '.ld'
            or re.fullmatch(r'core_.*\.h', path.name, re.I) is not None
            or (path.name.lower().startswith('startup_') and path.suffix.lower() == '.s')
            or 'cmsis' in parts
            or any(part.endswith('hal_driver') for part in parts))


def generated(path, before):
    if Path(path).suffix.lower() not in {'.c', '.h'}:
        return False
    parts = [part.lower() for part in Path(path).parts]
    root_file = any(parts[i:i + 2] in [['core', 'src'], ['core', 'inc']]
                    and len(parts[i + 2:]) == 1 for i in range(len(parts) - 2))
    known_root = (Path(path).name.lower() in {'main.c', 'main.h'}
                  or re.fullmatch(r'stm32\w+_(?:it|hal_msp)\.[ch]', Path(path).name, re.I))
    return '/* USER CODE BEGIN' in before or (root_file and bool(known_root))


def generated_signature(text):
    """Discard only block contents; retain every generated byte and delimiter."""
    signature, active = [], None
    for line in text.splitlines(keepends=True):
        match = MARKER.fullmatch(line.rstrip('\r\n'))
        if match:
            action, name = match.groups()
            if action == 'BEGIN':
                if active is not None:
                    raise PolicyError('Nested USER CODE blocks.')
                active = name
            elif active != name:
                raise PolicyError('Unmatched USER CODE delimiter.')
            else:
                active = None
            signature.append(line)
        elif '/* USER CODE BEGIN' in line or '/* USER CODE END' in line:
            raise PolicyError('Malformed USER CODE delimiter.')
        elif active is None:
            signature.append(line)
    if active is not None:
        raise PolicyError('Unclosed USER CODE block.')
    return ''.join(signature)


def code_tokens(text):
    # Preserve line boundaries so a removed comment cannot join identifiers.
    return LEXICAL.sub(lambda match: '\n' * match.group().count('\n') + ' ', text)


def validate_change(path, before, after, *, whole_write=False, allow_protected=()):
    if after is not None and Path(path).suffix.lower() in BINARY_SUFFIXES:
        raise PolicyError('Keep compiled artifacts out of Git; use the build/artifact workflow.')
    if protected(path) and str(Path(path).resolve()) not in allow_protected:
        raise PolicyError(f'Protected vendor/system file: {Path(path).name}.')
    if generated(path, before) and before:
        if after is None or whole_write:
            raise PolicyError('Use checked edits inside existing USER CODE blocks.')
        if generated_signature(before) != generated_signature(after):
            raise PolicyError('Generated text or USER CODE delimiters would change.')
    if after is None or Path(path).suffix.lower() not in SOURCE_SUFFIXES:
        return
    old_code, new_code = code_tokens(before), code_tokens(after)
    if Counter(ALLOC.findall(new_code)) - Counter(ALLOC.findall(old_code)):
        raise PolicyError('New dynamic allocation call in runtime source.')
    parts = {part.lower() for part in Path(path).parts}
    if parts & {'app', 'application', 'domain'}:
        if Counter(HAL.findall(new_code)) - Counter(HAL.findall(old_code)):
            raise PolicyError('Move new HAL/register access to bsp, drivers, or interface.')
