name: Firmware Release

on:
  push:
    tags:
      - 'v*' # tag needs to start with 'v' followed by version number, e.g., v1.0.0

jobs:
  # ==========================================
  # 1. Create Release
  publish-release:
    name: Publish Release
    permissions:
      contents: write
    uses: ARTTU-Software/.github/.github/workflows/create-release.yml@main