name: CI Tests
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  run-tests:
    permissions:
      contents: read
      pull-requests: write
      checks: write
    uses: ARTTU-Software/.github/.github/workflows/ceedling-test.yml@main