name: CI Tests
on: [push, pull_request]
jobs:
  run-tests:
    permissions:
      contents: read
      pull-requests: write
      checks: write
    uses: ARTTU-Software/.github/.github/workflows/ceedling-test.yml@main